name: CI/CD Pipeline for Bikeshare Model API

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  # Job 1: Train the model
  train_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install model dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bikeshare_project/requirements/requirements.txt

      - name: Train the model
        run: python bikeshare_project/bikeshare_model/train_pipeline.py

      - name: Upload trained model to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bikeshare_model
          path: bikeshare_project/bikeshare_model/trained_models/bikeshare__model_output_v0.0.1.pkl


  # Job 2: Test the model
  test_build:
    runs-on: ubuntu-latest
    needs: train_model
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bikeshare_project/requirements/test_requirements.txt

      - name: Download trained model artifacts
        uses: actions/download-artifact@v4
        with:
          name: bikeshare_model
          path: bikeshare_project/bikeshare_model/trained_models/

      - name: Run tests
        run: |
          # Assuming you have test files in the 'tests' directory
          pytest bikeshare_project/

      - name: Install and Build python package
        run: |
          pip install build
          python -m build bikeshare_project/

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: bikeshare_artifact
          path: bikeshare_project/dist/bikeshare_model-0.0.1-py3-none-any.whl

  test_dockerize:
    runs-on: ubuntu-latest
    needs: test_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Download trained model artifacts
        uses: actions/download-artifact@v4
        with:
          name: bikeshare_artifact
          path: bikeshare_project/bike_sharing_api/

      - name: Install and test package
        run: |
          pip install -r bikeshare_project/requirements/test_requirements.txt
          pip install bikeshare_project/bike_sharing_api/*.whl
          pytest bikeshare_project/ 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build docker image
        run: |
          cd bikeshare_project/bike_sharing_api/
          docker build -t chandra1697/bikeshare_api:v0.0.2 .

      - name: Push docker image
        run: docker push chandra1697/bikeshare_api:v0.0.2