name: CI/CD Pipeline for Bikeshare Model API

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  # Job 1: Train the model
  train_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install model dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bikeshare_project/requirements/requirements.txt

      - name: Train the model
        run: python bikeshare_project/bikeshare_model/train_pipeline.py

      - name: Upload trained model to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bikeshare_model
          path: bikeshare_project/bikeshare_model/trained_models/bikeshare__model_output_v0.0.1.pkl


  # Job 2: Test the model
  test_model:
    runs-on: ubuntu-latest
    needs: train_model
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bikeshare_project/requirements/test_requirements.txt

      - name: Download trained model artifacts
        uses: actions/download-artifact@v4
        with:
          name: bikeshare_model
          path: bikeshare_project/bikeshare_model/trained_models/

      - name: Run tests
        run: |
          # Assuming you have test files in the 'tests' directory
          pytest bikeshare_project/